categories = [
    "Adventure",
    "Ancient",
    "Animals",
    "Card Game",
    "City Building",
    "Civilization",
    "Dice",
    "Economic",
    "Educational",
    "Environmental",
    "Exploration",
    "Fantasy",
    "Farming",
    "Fighting",
    "Horror",
    "Mafia",
    "Maze",
    "Medical",
    "Medieval",
    "Music",
    "Mythology",
    "Party Game",
    "Pirates",
    "Puzzle",
    "Racing",
    "Science Fiction",
    "Sports",
    "Travel",
    "Trivia",
    "Wargame",
    "Zombies"
]

module.exports = { categories }